---
- name: Remove default Apache index page
  file:
    path: "{{ app_path }}/index.html"
    state: absent
  tags: 
   - app
   - index_cleanup

- name: Deploy application files
  template:
    src: index.php.j2
    dest: "{{ app_path }}/index.php"
  tags: 
   - app
   - deployment

