# ==========================================
# VM_GUARDIAN CONFIGURATION
# ==========================================

BACKUP_SRC="/home/sane/vbox_shared"
BACKUP_DEST="/home/sane/vbox_shared/VM_Guardian/archives"
LOG_FILE="/home/sane/vbox_shared/VM_Guardian/vm_guardian.log"
MAX_BACKUPS=7
