# ==========================================
# VM_GUARDIAN CONFIGURATION
# ==========================================

BACKUP_SRC="/home/sane/vbox_shared"
LOG_FILE="/home/sane/vbox_shared/VM_Guardian/vm_guardian.log"
MAX_BACKUPS=7


DEBIAN_IP="192.168.1.81"
ROCKY_IP="192.168.1.88"

DEBIAN_USER="sanedeb"
ROCKY_USER="sanerocky"


VM_LOG_SRC="/var/log/sysuu/"
