# ============================
# SYSPULSE CONFIGURATION FILE
# ============================

METRICS_LOG="/home/sane/first-devops-project/Sys_Pulse/syspulse_metrics/syspulse_metrics.csv"
ALERT_LOG="/home/sane/first-devops-project/Sys_Pulse/syspulse_logs/syspulse_alerts.log"
STATE_FILE="/home/sane/first-devops-project/Sys_Pulse/syspulse_logs/.last_failed_root"
AUTH_LOG_PATH="/var/log/auth.log"

CPU_THRESHOLD=80
RAM_THRESHOLD=85
DISK_MIN_FREE_PERCENT=10

CRITICAL_SERVICES="ssh nfs-kernel-server"
